### PR TITLE
Hindi translation part10 - Updated file

### PR DESCRIPTION
**Pull request by ruhi47**
Completed the issue #243  :

- I've translated the entire .md file from English to Hindi. This translation covers all sections and comments within the file, ensuring that the documentation is fully accessible to Hindi-speaking users.

- The structure and functionality of the content remain unchanged; only the language has been updated.

- The translation has been reviewed for accuracy and coherence. As this is a documentation change, no additional functional testing was required.

 - Unnecessary files removed, only updated file.

If any specific sections require further clarification or additional language support, please let me know. The translation is intended to make the documentation more accessible and user-friendly for Hindi speakers.

### CODE REVIEW

**Comment by rcallaby** [comment]
No, the unnecessary files are not removed. The persistence of your editor files in these commits continues. If you submit a pull request and it has more than say three files changed then you may have a problem. Look at your commit history. Why is it so large.

I use git pull to sync my git repo to the remote repo, are you doing the same?

**Comment by rcallaby** [comment]
Here is an article I think you may find helpful: 

https://stackoverflow.com/questions/11124053/accidentally-committed-idea-directory-files-into-git

**Comment by ruhi47** [comment]
I do git pull every time before starting to change anything, It has never happed before but could be something, let me go through the article. Thank you!

**Comment by ruhi47** [comment]
Does it look better now?
Thank you for bearing through!

**Review by rcallaby — APPROVED** [review]
Excellent! Thanks for sticking with it and for translating the lesson. I truly appreciate your hard work.

**Comment by ruhi47** [comment]
No worries! Thank you for teaching me that, I am very new to Open Source !

**Pull request merged**
