### PR TITLE
[Feat]: A Cron Job for Stale

### LINKED ISSUE #141: Github Action - Remove stale pull requests after 21 days
**Is your feature request related to a problem? Please describe.**
Yes, I want to add a github action that is activated daily that will automatically archive stale pull requests. Basically, after 21 days any pull request that has no activity on it will be automatically archived or in some way removed so that only active pull requests remain.

**Describe the solution you'd like**
A Github action yaml file created with a cron job that runs every day and that after 21 days of inactivity a pull request is either removed or archived.

**Describe alternatives you've considered**
The only other alternative, which isn't ideal is to review every single pull request every day manually, and that could become laborious over time.

### LINKED ISSUE #143: Github Action - Remove stale Issue after 60 days
**Is your feature request related to a problem? Please describe.**
Yes, I want to add a github action that is activated daily that will automatically archive stale issues. Basically, after 60 days any issue that has no activity on it will be automatically archived or in some way removed so that only active issues remain.

**Describe the solution you'd like**
A Github action yaml file created with a cron job that runs every day and that after 60 days of inactivity an issue is either removed or archived.

**Describe alternatives you've considered**
The only other alternative, which isn't ideal is to review every single issue every day manually, and that could become laborious over time.

### PR DESCRIPTION
**Pull request by Petsamuel**
resolved #143 
 resolved #141

### CODE REVIEW

**Comment by rcallaby** [comment]
So to be clear this will clean up both stale issues and PRs in one go? Because I had two seperate requirement sets for PRs and Issues, that is why I seperated them.

**Review by rcallaby — CHANGES_REQUESTED** [review]
This does both PRs and Issues, whereas I needed one for PRs and one for Issues as I feel they need seperate requirements. Can you change it so it fits the requirements of the issue. please?

**Comment by Petsamuel** [comment]
> This affects stale pull requests, however, you were assigned the stale issues, as well the number of days is too long for stale pull requests as it should be only 21 days, not 60.
> 
> So, to be clear.
> 
> 1. Change this to issues
> 2. The number of days for issues is 60 so this is fine.
> 
> If you want to also do the stale pull requests please just ask to be assigned it and I will do that.

Sorry for the mix-up. I have worked on both issues, you can assign the other to me as well

**Review by rcallaby — APPROVED** [review]
Great job! Thank you for your contributions.

**Pull request merged**
