### PR TITLE
Added links to Table of Contents for Part-01

### PR DESCRIPTION
**Pull request by TFM-HITESH**
Have completed Issue #80 and have added the required links to the table of contents. It now correctly navigates to the required section on click. Also added an additional Item in Table of Contents for "Introduction"

### CODE REVIEW

**Review by rcallaby — APPROVED** [review]
Looks great.

**Comment by TFM-HITESH** [comment]
Thank you !

**Comment by rcallaby** [comment]
Closed #80

**Comment by TFM-HITESH** [comment]
Sorry for accidentally closing the PR, new to github

**Pull request merged**
