### PR TITLE
Added Fork Image

### PR DESCRIPTION
**Pull request by RileeyL**
I added a fork image to the First-Contributions tutorial page. However, I was sadly not able to add an image to the other steps as I was not sure how they would look for other people and I did not want the page to look too messy. I do hope you will accept at least my one image as this is my first time ever submitting a pull request and using open-source in general. Thank you and have a good day, if you have any tips please let me know!

### CODE REVIEW

**Review by rcallaby — CHANGES_REQUESTED** [review]
I know you may be nervous when submitting your first contribution but I can't really accept this as it is incomplete.

As well, you added yet another folder called assets when there was an /images folder already in the repository. I simply can't have this repository getting out of control with the number of folders.

My tip would be to keep trying and research how to do things through Google and YouTube. Keep at it, you can do it.

**Comment by RileeyL** [comment]
> I know you may be nervous when submitting your first contribution but I can't really accept this as it is incomplete.
> 
> As well, you added yet another folder called assets when there was an /images folder already in the repository. I simply can't have this repository getting out of control with the number of folders.
> 
> My tip would be to keep trying and research how to do things through Google and YouTube. Keep at it, you can do it.

Thank you for your tips, I am very sorry for not doing it right.

**Comment by rcallaby** [comment]
No, I am not going to report this as spam as you clearly made an effort to contribute. Although I am a bit disappointed you gave up so quickly. You could've finished it if you kept at it.

Can you at least try and add your name to the contributors.md file? That should help build confidence in the future.

**Comment by RileeyL** [comment]
> No, I am not going to report this as spam as you clearly made an effort to contribute. Although I am a bit disappointed you gave up so quickly. You could've finished it if you kept at it.
> 
> Can you at least try and add your name to the contributors.md file? That should help build confidence in the future.

Sorry about not finishing, its just that when I was trying to show an example image of inputting the text into the Git application, some of the command prompts were not working. Me and my friend were working on it for several hours but we just couldn't seem to figure out why it was not working as it should. Although thanks for at least giving me the opportunity because It helped me understand hacktoberfest much better.

**Pull request closed without merging**
