### PR TITLE
Added two images to part 03

### PR DESCRIPTION
**Pull request by AlexVCS**
working on #127

### CODE REVIEW

**Review by rcallaby — CHANGES_REQUESTED** [review]
While I appreciate the contribution this doesn't fit the requirements of this issue. You supplied me with screenshots, not illustrative images of branching and merging. I was looking for something that illustrated graphically branching and merging.

For instance, the images used here: 
https://gauravjanjal16.hashnode.dev/git-branching-and-merging

Illustrate Branching and Merging.

**Comment by AlexVCS** [comment]
> While I appreciate the contribution this doesn't fit the requirements of this issue. You supplied me with screenshots, not illustrative images of branching and merging. I was looking for something that illustrated graphically branching and merging.
> 
> For instance, the images used here: https://gauravjanjal16.hashnode.dev/git-branching-and-merging
> 
> Illustrate Branching and Merging.

Ok thanks, I wasn't quite sure what to go for, I'll change it.

**Comment by AlexVCS** [comment]
Please let me know what you think of this

**Review by rcallaby — APPROVED** [review]
Looks great, thank you for your contribution.

**Pull request merged**
